config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :accounts,
    path: '/',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'signup'
    }

  devise_for :admin_accounts,
    path: 'admin',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
    }

  namespace :admin do

    get '/',
      controller: 'base',
      action: 'index'

  end

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :attachable,
    polymorphic: true

  mount_uploader :attachment, AttachmentUploader

  before_create :set_meta

  def extension
    File.extname(name)
  end

  private

    def set_meta
      return unless attachment

      self.name = File.basename(attachment.to_s)
      self.filesize = attachment.file.size
    end

end

app/controllers/admin/attachments_controller.rb
module Admin
  class AttachmentsController < BaseController

    include AttachmentActions

  end
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    skip_before_action :authenticate_account!
    before_action :authenticate_admin_account!, unless: :devise_controller?

    layout 'admin'

    def index
      render 'admin/index'
    end

    def become_account
      account = Account.find(params[:id])
      sign_out(current_account) if current_account
      sign_in(:account, account, bypass: true)
    end

    def in_admin?
      true
    end
    helper_method :in_admin?

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  cattr_accessor :raise_on_unathorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :store_request_variables
  before_action :authenticate_account!
  before_action :authorize_account, unless: :devise_controller?

  def in_admin?
    false
  end
  helper_method :in_admin?

  def page_title=(page_title)
    @page_title = page_title
  end
  helper_method :page_title=

  def page_title
    if @page_title
      "#{@page_title} | #{Config.site_name}"
    else
      Config.site_name
    end
  end
  helper_method :page_title

  private

    def store_request_variables
      RequestStore.store[:current_account] = current_account
      RequestStore.store[:current_admin_account] = current_admin_account
    end

    def current_permission
      @current_permission ||= Permissions.for(controller_name, current_account)
    end

    def current_resource
      nil
    end

    def authorize_account
      unless current_permission.action_allowed?(controller_name, action_name, current_resource)
        if ApplicationController.raise_on_unathorized or Rails.env.development?
          raise "Not Authorized: #{current_permission.class} #{controller_name}##{action_name}"
        else
          redirect_to(not_authorized_path)
        end
      end
    end

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController

  include AttachmentActions

end

app/controllers/attchments_controller.rb
class AttachmentsController < ApplicationController

  include AttachmentActions

end

app/controllers/concerns/attachments_actions.rb
module AttachmentActions
  extend ActiveSupport::Concern

  included do
    include ActionView::Helpers::UrlHelper
  end

  def dnd
    attachable = dnd_params[:attachable_type].constantize.find(dnd_params[:attachable_id])
    attachment_type = dnd_params[:attachment_type]

    # is it's a has_one, get rid of the old one first
    if 'undefined' != attachment_type and not attachable.send(attachment_type).respond_to?(:<<)
      attachable.send(attachment_type).try(:destroy)
    end

    attachment = Attachment.create!(
      attachable: attachable,
      attachment: dnd_params[:file],
      attachment_type: dnd_params[:attachment_type]
    )

    if 'undefined' != dnd_params[:target]
      markup = nil

      url = case dnd_params[:size]
        when 'thumb'
          attachment.attachment.thumb.url
        when 'mini'
          attachment.attachment.mini.url
        when 'link'
          markup = link_to attachment.name, attachment.attachment.url
        else
          attachment.attachment.url
      end

      render json: {
        target: dnd_params[:target],
        url: url,
        markup: markup
      }
    else
      markup = render_to_string(partial: 'shared/attachment', locals: { attachment: attachment.decorate })
      render json: { markup: markup, attachment: attachment.as_json(methods: [:filename]) }
    end
  end

  def destroy
    current_resource.destroy
    render nothing: true
  end

  private

    def dnd_params
      params.permit!
    end

    def current_resource
      Attachment.find_by_id(params[:id])
    end

end

app/controllers/concerns/public_controller.rb
module PublicController
  extend ActiveSupport::Concern

  included do
    skip_before_action :authenticate_account!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def yes_no(bool)
    bool ? 'Yes' : 'No'
  end

  def active?(controller)
    controller == controller_name
  end

  def active_class(controller)
    "active" if active?(controller)
  end

  def action_active?(action)
    action == action_name
  end

  def action_active_class(action)
    "active" if action_active?(action)
  end

  def flash_class(level)
    case level.to_sym
      when :notice
        "alert alert-info"
      when :success
        "alert alert-success"
      when :error
        "alert alert-error"
      when :alert
        "alert alert-warning"
    end
  end

end

app/helpers/date_helper.rb
module DateHelper

  def short_date(date)
    return date unless date.respond_to?(:strftime)

    month = date.strftime('%B')
    day = date.strftime('%e').to_i.ordinalize

    "#{month} #{day}"
  end

  def long_date(date)
    return date unless date.respond_to?(:strftime)

    month = date.strftime('%B')
    day = date.strftime('%e').to_i.ordinalize
    year = date.year

    "#{month} #{day}, #{year}"
  end

  def long_date_with_zone(date)
    return date unless date.respond_to?(:strftime)

    date.strftime('%B %e at %r %Z')
  end

  def short_date_with_zone(date)
    return date unless date.respond_to?(:strftime)

    date.strftime('%b %e at %r %Z')
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="site-header" role="banner">
      <%= render :partial => 'admin/shared/header' %>
    </header>

    <div class="flash-messages">
      <%= render 'shared/flash_messages' %>
    </div>

    <main role="main" class="container">
      <%= yield %>
    </main>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">&copy; <%%= Date.today.year %> <%%= Config.site_name %></p>
      </div>
    </footer>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/favicon.ico">

    <title><%%= page_title %></title>

    <%%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%%= csrf_meta_tags %>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%%= link_to Config.site_name, root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%%= active_class(controller_name) %>">
              <%%= link_to 'Home', root_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <%% if current_account %>
              <li class="dropdown pull-right">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="#">Action</a>
                  </li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">
                    My Account
                  </li>
                  <li>
                    <%%= link_to 'Change Password', edit_account_password_path %>
                  </li>
                  <li>
                    <%%= link_to 'Log out', destroy_account_session_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <%% else %>
              <li>
                <%%= link_to 'Sign Up', new_account_registration_path %>
              </li>
              <li>
                <%%= link_to 'Sign In', new_account_session_path %>
              </li>
            <%% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <%%= render 'shared/flash_messages' %>
      <%%= yield %>
    </div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">&copy; <%%= Date.today.year %> <%%= Config.site_name %></p>
      </div>
    </footer>

  </body>
</html>

app/views/pages/home.html.erb
<div class="page-header">
  <h1>This is the home page</h1>
</div>
<p class="lead">
  Find me in app/views/pages/home.html.erb
</p>

app/views/shared/_flash_messages.html.erb
<%% flash.each do |key, value| %>
  <%% if value.present? %>
    <div class="alert <%%= flash_class(key) %> alert-dismissible fade in">
      <div class="flash-message">
       <%%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <%% end %>
<%% end %>